// The following directive is necessary to make the package coherent:

//go:build ignore
// +build ignore

// This program generates version.go. It can be invoked by running
// go generate
package main

import (
	"log"
	"os"
	"text/template"
	"time"

	"github.com/cipto-hd/greenlight/internal/vcs"
)

func main() {
	f, err := os.Create("version.go")
	die(err)
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Version   string
	}{
		Timestamp: time.Now(),
		Version:   vcs.Version(),
	})
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package greenlight

var Version = "{{ .Version }}"
`))
