// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2024-02-23 08:49:37.397218273 +0700 WIB m=+0.000363068
package greenlight

var Version = "v1.0.0-11-g86b2c51-dirty"
